### ISSUE TITLE
运行在1.21 spigot快照版本中无法加载此插件

### ISSUE THREAD

**Issue by maaaxinfinity** [RTAkland/YeeeesMOTD#5]
以下为部分报错日志
```
[20:20:14] [Server thread/ERROR]: Could not load 'plugins/YeeeesMOTD.jar'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/MiniMessage
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:313) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:122) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:464) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4267-Spigot-5bbef5a-403accd]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4267-Spigot-5bbef5a-403accd]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4267-Spigot-5bbef5a-403accd]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4267-Spigot-5bbef5a-403accd]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/MiniMessage
        at cn.rtast.yeeeesmotd.paper.YeeeesMOTDPlugin.<clinit>(YeeeesMOTDPlugin.kt:31) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.minimessage.MiniMessage
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at cn.rtast.yeeeesmotd.paper.YeeeesMOTDPlugin.<clinit>(YeeeesMOTDPlugin.kt:31) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 8 more
```

使用的YeeeesMOTD版本为：1.3.7
使用的服务器核心版本为：CraftBukkit version 4267-Spigot-5bbef5a-403accd (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)

由于当时GetBukkit官网下载1.21核心后运行提示警告**outdated**，于是本人前往spigot官网下载构建器自行构建了此版本
故此给出我的核心链接：https://wwo.lanzouw.com/iyGYp24t247e 密码:ah4j

服务器目录下运行有以下插件：
![image](https://github.com/user-attachments/assets/b0686d37-ba8c-4abd-a033-600f53809a7d)
---
望解决，谢谢😭

**Comment by RTAkland** [comment]
请问你下载的是哪个版本呢 bukkit? paper?

**Comment by RTAkland** [comment]
你应该是下载错版本了，spigot服务端需要使用bukkit api来运行， 所以请下载文件名bukkit字样的插件

**Comment by RTAkland** [comment]
我使用你提供的服务端使用YeeeesMOTD-spigot+bukkit+mc.1.21.6a81d0b-1.3.7-all.jar测试成功

**Comment by maaaxinfinity** [comment]
> 你应该是下载错版本了，spigot服务端需要使用bukkit api来运行， 所以请下载文件名bukkit字样的插件

确实是，昨晚熬夜脑子不太行，下错了
感谢作者给予帮助💕
