### ISSUE TITLE
1.20.1 velocity无法加载

### ISSUE THREAD

**Issue by MineYF** [RTAkland/YeeeesMOTD#8]
不知道是不是我下载版本的问题，我在modrinth根据版本选择下载了YeeeesMOTD-paper.5eea821-1.4.0-all版本，加入后velocity无法识别
[19:17:24] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Booting up Velocity 3.4.0-SNAPSHOT (git-cefa3b27-b450)...
[19:17:24] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loading localizations...
[19:17:24] [main/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Connections will use NIO channels, Java compression, Java ciphers
[19:17:24] [main/WARN] [com.velocitypowered.proxy.config.VelocityConfiguration]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[19:17:24] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loading plugins...
[19:17:24] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Unable to load plugin plugins\YeeeesMOTD-paper.5eea821-1.4.0-all.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file YeeeesMOTD-paper.5eea821-1.4.0-all.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:161) ~[velocity-3.4.0-SNAPSHOT-450.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:62) ~[velocity-3.4.0-SNAPSHOT-450.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:101) ~[velocity-3.4.0-SNAPSHOT-450.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:418) ~[velocity-3.4.0-SNAPSHOT-450.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:289) ~[velocity-3.4.0-SNAPSHOT-450.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity-3.4.0-SNAPSHOT-450.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
[19:17:24] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loaded 1 plugins
[19:17:24] [Netty NIO Boss #0/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Listening on /[0:0:0:0:0:0:0:0]:25577
[19:17:24] [main/INFO] [com.velocitypowered.proxy.Velocity]: Done (0.36s)!

**Comment by RTAkland** [comment]
velocity没有版本之分，只要vc的版本在3.3以上都可以用，vc平台需要下载文件名中包含`velocity`的jar文件, 你下载的平台是paper版本

**Comment by RTAkland** [comment]
![image](https://github.com/user-attachments/assets/666106e3-a36e-45d8-8fe1-cc830ef34b85)
下载这个

**Comment by MineYF** [comment]
原来在这，而且不支持Java17 我现在可以使用了 谢谢

**Comment by RTAkland** [comment]
忘记说了，因为现在主流的服务端都是java21，所以我才选择都用jdk21进行开发的
